### ISSUE TITLE
InferenceSession load error on linux 

### ISSUE THREAD

**Issue by Taruu** [w-e-w/sd-webui-nudenet-nsfw-censor#1]
Hello! I am install you ext on my linux machine, and get a simple error:
```*** Error loading script: api.py
    Traceback (most recent call last):
      File "/mnt/500disk/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/500disk/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/mnt/500disk/stable-diffusion-webui/extensions/sd-webui-nudenet-nsfw-censor/scripts/api.py", line 1, in <module>
        from scripts.pil_nude_detector import pil_nude_detector, nudenet_labels_index, mask_shapes_func_dict
      File "/mnt/500disk/stable-diffusion-webui/extensions/sd-webui-nudenet-nsfw-censor/scripts/pil_nude_detector.py", line 193, in <module>
        pil_nude_detector = PilNudeDetector()
      File "/mnt/500disk/stable-diffusion-webui/extensions/sd-webui-nudenet-nsfw-censor/scripts/pil_nude_detector.py", line 69, in __init__
        self.onnx_session = InferenceSession(Path(__file__).parent.parent.joinpath('nudenet', 'best.onnx'))
      File "/home/taruu/.local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 336, in __init__
        raise TypeError("Unable to load from type '{0}'".format(type(path_or_bytes)))
    TypeError: Unable to load from type '<class 'pathlib.PosixPath'>'
```

To fix this you need add `str()` func
`self.onnx_session = InferenceSession(str(Path(__file__).parent.parent.joinpath('nudenet', 'best.onnx')))`

**Comment by w-e-w** [comment]
thanks, wonder why doesn't work on Linux
fix 69efedfd267c7e210038058662ff18649ba6da4e
